themes:
  defaultAppearance: light
  appearanceSwitcher: true
  colors:
    primary:
      light: "#ff0000"
      dark: "#00ff00"
    myCustomColor:
      light: "#abcdef"
      dark: "#fedcba"

plugins:
  components:
    # This loads all of evidence's core charts and UI components
    # You probably don't want to edit this dependency unless you know what you are doing
    "@evidence-dev/core-components": {}

  datasources:
    # You can add additional datasources here by adding npm packages. 
    # Make to also add them to `package.json`.
    "@evidence-dev/bigquery": { }
    "@evidence-dev/csv": { }
    "@evidence-dev/databricks": { }
    "@evidence-dev/duckdb": { }
    "@evidence-dev/mssql": { }
    "@evidence-dev/mysql": { }
    "@evidence-dev/postgres": { }
    "@evidence-dev/snowflake": { }
    "@evidence-dev/sqlite": { }
    "@evidence-dev/trino": { }
    "@evidence-dev/motherduck": { }
